version: '3'
services:
    node:
        build: .
        volumes:
            - .:/usr/src/app
        # working_dir: /usr/src/app/nextjs-blog
        # command: npm run dev
        ports:
            - "3000:3000"
