version: '3'
services:
    node:
        build: .
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app/my-next-app
        command: npm run dev
        ports:
            - "3000:3000"
        networks:
            - shared-network

networks:
    shared-network:
        external: true
